
ARTIFACT_DIR: str = "artifacts"
PIPE_NAME: str = "DataValidation"
TARGET_COL_NAME: str = "Result"
INGESTION_DIR: str = "data_ingestion"
TRAIN_FILE_NAME: str = "train.csv"
TEST_FILE_NAME: str = "test.csv"
DATA_VALIDATION_VALID_DIR: str = "validated"
DATA_VALIDATION_INVALID_DIR: str = "invalid"
DATA_VALIDATION_DRIFT_REPORT_DIR: str ="validation_report"
DATA_VALIDATION_DRIFT_REPORT_FILE: str = "validatoin_report.yaml"
SCHEMA_DIR: str = "schema.yaml"